name: Sean's Blog
url: http://example.org
description: A halfway house is a destination for no-one..

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']